name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-dark.svg?color_snake=%235BC0BE&color_dots=%2321262d,%231d4f4d,%232c807c,%2342a6a2,%235bc0be
            dist/snake-light.svg?color_snake=%2317817F&color_dots=%23ebedf0,%23c6e8e6,%2394d5d1,%235bc0be,%2317817f

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
